FROM golang:1.24.2 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN go build -o rabbit-consumer main.go

FROM gcr.io/distroless/base-debian12
COPY --from=builder /app/rabbit-consumer /rabbit-consumer

CMD ["/rabbit-consumer"]