# Etapa 1: build
FROM golang:1.24.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN go build -o kafka_writer ./server/writer_kafka/main.go

# Etapa 2: runtime
FROM gcr.io/distroless/base-debian12

COPY --from=builder /app/kafka_writer /kafka_writer

EXPOSE 50052

ENTRYPOINT ["/kafka_writer"]
